### ISSUE TITLE
Four feature requests on Citadel

### ISSUE THREAD

**Issue by Kakcalu13** [ignitionrobotics/ign-gazebo#1108]
Hi there,

I wanted to request if it is possible to add those new features on IGN Citadel (and for Fortress if they don't have it on #2 and #1) 

1) Change the background color
![image](https://user-images.githubusercontent.com/65916520/137382830-04788dc8-800d-4308-891a-084835a96bf9.png)

Like change the white background to neon green, blue or any color. (I know this will impact on preferences only)

2) Able to toggle to remove the grid on the floor
![image](https://user-images.githubusercontent.com/65916520/137382997-6d6cbf9d-3b27-4a18-9f15-d2eca19a7f1a.png)

3) Add the `--headless-rendering` and `<heightmap>` feature on Citadel :angel:

**Comment by chapulina** [comment]
1. You can change it through SDF. Changing through the GUI is not possible yet, see https://github.com/ignitionrobotics/ign-gazebo/issues/246. SDF example:

    Change for sensors:

        https://github.com/ignitionrobotics/ign-gazebo/blob/fc2a98ec5e1b149d773eeb6cae4a407bd82a81a2/examples/worlds/tunnel.sdf#L19

    Change for the GUI:

        https://github.com/ignitionrobotics/ign-gazebo/blob/fc2a98ec5e1b149d773eeb6cae4a407bd82a81a2/examples/worlds/tunnel.sdf#L37

1. Doable from the GUI and from SDF.

    See https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo5/examples/worlds/grid.sdf for the GUI and for SDF:

    https://github.com/ignitionrobotics/ign-gazebo/blob/fc2a98ec5e1b149d773eeb6cae4a407bd82a81a2/examples/worlds/tunnel.sdf#L20

1. That's not possible because it would break backwards compatibility. You'll need to upgrade to a newer version.

---

> add those new features

In the future, please open a separate issue for each. If they were indeed features that were missing, it would be confusing to track them all into the same ticket.

---

If you're motivated, it would be great to add a tutorial explaining how to change these scene properties that you found, so others can reference it in the future :wink: 

---

Closing this ticket because there's nothing left to be addressed.
